/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.cliente;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.security.Security;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.Scanner;

import com.google.gson.GsonBuilder;

import gui.cliente.Bloque;
import gui.cliente.EntradaTransaccion;
import gui.cliente.SalidaTransaccion;
import gui.cliente.Transaccion;

/**
 *
 * @author pc
 */
public class Principal extends javax.swing.JFrame {
	
	public static ArrayList<Bloque> cadenaBloques = new ArrayList<Bloque>();
	public static HashMap<String,SalidaTransaccion> UTXOs = new HashMap<String,SalidaTransaccion>();
	
	public static int dificultad = 3;
	public static float transaccionMinima = 0.1f;
	public static Cartera carteraPagador;
	public static Cartera carteraRecaudador;
	public static Transaccion transaccionOrigen;
	
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("   Cliente");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setText("Iniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Introduzca el saldo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Introduzca el importe: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Introduzca la cantidad a entregar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(1, 1, 1)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	
    	int saldo = (Integer)jSpinner1.getValue();
    	int importe = (Integer)jSpinner2.getValue();
    	int cantidad = (Integer)jSpinner3.getValue();
    	
    	if (saldo<=0) {
    		System.out.println("El saldo debe ser mayor que 0");
    	} else if (importe<=0) {
    		System.out.println("El importe debe ser mayor que 0");
    	  } else if (cantidad<=0) {
      			System.out.println("La cantidad debe ser mayor que 0");
      	    } else if (saldo>0 && importe>0 && cantidad>0) {
      	    	if (cantidad<importe) {	
      	    		System.out.println("La cantidad debe ser mayor o igual que el importe");
      	    	  } else {
      	    		  comenzar();
      	    		}
      	    	}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void comenzar() {
    	
    	//Se aï¿½aden los bloques al ArrayList cadenaBloques:
    	Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider()); //Se utiliza Bouncey castle como proveedor de seguridad
    			
    	//Creaciï¿½n de las carteras:
    	carteraPagador = new Cartera();
    	carteraRecaudador = new Cartera();		
    	Cartera euro = new Cartera();
    	
    	//Host del servidor
        final String HOST = "127.0.0.1";
        //Puerto del servidor
        final int PUERTO = 5000;
        DataInputStream in;
        DataOutputStream out;
 
        try {
            //Creo el socket para conectarme con el cliente
            Socket sc = new Socket(HOST, PUERTO);
 
            in = new DataInputStream(sc.getInputStream());
            out = new DataOutputStream(sc.getOutputStream());
 
            Scanner teclado = new Scanner(System.in);
    		
    		int balance = (Integer)jSpinner1.getValue();
    		int value = (Integer)jSpinner2.getValue();
    		int quantity = (Integer)jSpinner3.getValue();
    		
    		float saldo = balance;
    		float importe = value;
    		float cantidad = quantity;
    		
    		String cadenaSaldo = Float.toString(saldo);
    		String cadenaImporte = Float.toString(importe);
    		String cadenaCantidad = Float.toString(cantidad);
    		
    		out.writeUTF(cadenaSaldo);
    		out.writeUTF(cadenaImporte);
    		out.writeUTF(cadenaCantidad);
    		
            //Creación de la transacción origen que añade el saldo en la cartera del pagador: 
        	transaccionOrigen = new Transaccion(euro.clavePublica, carteraPagador.clavePublica, saldo, null);
        	transaccionOrigen.generarFirma(euro.clavePrivada);	 //Se firma manualmente la transacción origen	
        	transaccionOrigen.idTransaccion = "0"; //Se asigna el id de la transacción manualmente
        	transaccionOrigen.salidas.add(new SalidaTransaccion(transaccionOrigen.destinatario, transaccionOrigen.valor, transaccionOrigen.idTransaccion)); //manually add the Transactions Output
        	UTXOs.put(transaccionOrigen.salidas.get(0).id, transaccionOrigen.salidas.get(0)); //Es importante almacenar la primera transacciï¿½n en la lista UTXOs.
        			
        	System.out.println("creando y minando el bloque origen... ");
        	Bloque origen = new Bloque("0");
        	origen.añadirTransaccion(transaccionOrigen);
        	añadirBloque(origen);
        	
        	//testing
        	Bloque bloque1 = new Bloque(origen.hash);
        	
        	if (cantidad<=saldo ) {
        		if (cantidad==importe) {
        			System.out.println("\nEl saldo de la cartera del pagador es de: " + carteraPagador.obtenerSaldo() + " €");
                	System.out.println("\nEl pagador entrega " + cantidad + " € al recaudador...");
                	bloque1.añadirTransaccion(carteraPagador.enviarDinero(carteraRecaudador.clavePublica, cantidad));
                	String cadenaCantidadEnviada = Float.toString(cantidad);
                	out.writeUTF(cadenaCantidadEnviada);
                	añadirBloque(bloque1);
                	System.out.println("\nEl saldo de la cartera del pagador es de: " + carteraPagador.obtenerSaldo() + " €");
                	System.out.println("el saldo de la cartera del recaudador es de: " + carteraRecaudador.obtenerSaldo() + " €");
        		} else if (cantidad>importe) {
        			System.out.println("\nEl saldo de la cartera del pagador es de: " + carteraPagador.obtenerSaldo() +  "€");
                	System.out.println("\nEl pagador entrega " + cantidad + " € al recaudador...");
                	bloque1.añadirTransaccion(carteraPagador.enviarDinero(carteraRecaudador.clavePublica, cantidad));
                	String cadenaCantidadEnviada = Float.toString(cantidad);
                	out.writeUTF(cadenaCantidadEnviada);
                	añadirBloque(bloque1);
                	System.out.println("\nEl saldo de la cartera del pagador es de: " + carteraPagador.obtenerSaldo() + " €");
                	System.out.println("el saldo de la cartera del recaudador es de: " + carteraRecaudador.obtenerSaldo() + " €");
                	
                	Bloque bloque2 = new Bloque(bloque1.hash);
                	String cadenaCambioRecibida = in.readUTF();
                	float cambioRecibido = Float.parseFloat(cadenaCambioRecibida);
                	System.out.println("\nEl recaudador devuelve " + cambioRecibido + " € al pagador...");
                	bloque2.añadirTransaccion(carteraRecaudador.enviarDinero(carteraPagador.clavePublica, cambioRecibido));
                	System.out.println("\nEl saldo de la cartera del pagador es de: " + carteraPagador.obtenerSaldo() + " €");
                	System.out.println("El saldo de la cartera del recaudador es de: " +carteraRecaudador.obtenerSaldo() + " €");
                	
        		  }
        	} else if (cantidad>saldo) {
        		Bloque bloque2 = new Bloque(bloque1.hash);
            	System.out.println("\nEl pagador quiere entregar más dinero del que tiene...");
           		bloque2.añadirTransaccion(carteraPagador.enviarDinero(carteraRecaudador.clavePublica, cantidad));
            	añadirBloque(bloque2);            	
        	  }  		
      		
        	esValidaCadena();
        	
            sc.close();
 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }
    
    public static Boolean esValidaCadena() {
		Bloque bloqueActual; 
		Bloque bloqueAnterior;
		String hashDestino = new String(new char[dificultad]).replace('\0', '0');
		HashMap<String,SalidaTransaccion> tempUTXOs = new HashMap<String,SalidaTransaccion>(); //Una lista funcional de transacciones sin gasto en el estado de un bloque dado.
		tempUTXOs.put(transaccionOrigen.salidas.get(0).id, transaccionOrigen.salidas.get(0));
		
		//Recorrido de la cadena de bloques paraa comprobar los hashes:
		for(int i=1; i < cadenaBloques.size(); i++) {
			
			bloqueActual = cadenaBloques.get(i);
			bloqueAnterior = cadenaBloques.get(i-1);
			//Comparación del hash registrado con el calculado:
			if(!bloqueActual.hash.equals(bloqueActual.calcularHash()) ){
				System.out.println("#Los hashes actuales no son iguales");
				return false;
			}
			//Comparación del hash anterior con el registrado
			if(!bloqueAnterior.hash.equals(bloqueActual.hashAnterior) ) {
				System.out.println("#Los hashes anteriores no son iguales");
				return false;
			}
			//Comprobar si el hash se ha resuelto
			if(!bloqueActual.hash.substring( 0, dificultad).equals(hashDestino)) {
				System.out.println("#Este bloque no ha sido minado");
				return false;
			}
			
			//Recorrido de las transacciones de la cadena de bloques:
			SalidaTransaccion tempSalida;
			for(int t=0; t <bloqueActual.transacciones.size(); t++) {
				Transaccion transaccionActual = bloqueActual.transacciones.get(t);
				
				if(!transaccionActual.verificarFirma()) {
					System.out.println("#La firma de la transacción(" + t + ") es inválida");
					return false; 
				}
				if(transaccionActual.obtenerValorEntradas() != transaccionActual.obtenerValorSalidas()) {
					System.out.println("#Las entradas de la transaccion (" + t + ") no son iguales a las salidas");
					return false; 
				}
				
				for(EntradaTransaccion entrada: transaccionActual.entradas) {	
					tempSalida = tempUTXOs.get(entrada.idSalidaTransaccion);
					
					if (tempSalida == null) {
						System.out.println("#Falta la entrada referenciada de la transacción (" + t + ")");
						return false;
					}
					
					if (entrada.UTXO.valor != tempSalida.valor) {
						System.out.println("#El valor de la entrada referenciada de la transacción (" + t + ") es inválido");
						return false;
					}
					
					tempUTXOs.remove(entrada.idSalidaTransaccion);
				}
				
				for (SalidaTransaccion salida: transaccionActual.salidas) {
					tempUTXOs.put(salida.id, salida);
				}
				
				if (transaccionActual.salidas.get(0).destinatario != transaccionActual.destinatario) {
					System.out.println("#El destinatario de la salida de la transaccion(" + t + ") no es quien debería ser.");
					return false;
				}
			
				if (transaccionActual.salidas.get(1).destinatario != transaccionActual.destinatario) {
					System.out.println("#El 'cambio' de la salida de la transacción(" + t + ") no es del remitente.");
					return false;
				}
				
			}
			
		}
		System.out.println("La cadena de bloques no es válida");
		return true;
    }

    private static void añadirBloque(Bloque nuevoBloque) {
		nuevoBloque.minarBloque(dificultad);
		cadenaBloques.add(nuevoBloque);
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    // End of variables declaration//GEN-END:variables
}
